#!/bin/bash

for i in {1..15}
do
    for j in {1..3}
    do
        python main.py \
            -type=memcached \
            -server-conf=../configs/cpu-vs-latency/memcached.conf \
            -memtier-conf=../configs/cpu-vs-latency3/memtier.memcached.$i.conf \
            -output=../results/cpu-vs-latency2/memcached/$((i+15))-$j/
    done
done
