#!/bin/bash

DIR=multiple-instances

INSTANCES=1

for i in {1..7}
do
    python ../../../benchmark/main.py \
        -type=memcached \
        -server-conf=./memcached.$i.conf \
        -memtier-conf=./memtier.memcached.$i.conf \
        -output=../../../results/baseline/$DIR/$i/ \
        -base-port=11120 \
        -instances=$INSTANCES \
        -duration=30
    INSTANCES=$((INSTANCES * 2))
done
