#!/bin/bash

DIR=object-size

for i in {1..20}
do
    python ../../../benchmark/main.py \
        -type=memcached \
        -server-conf=./memcached.conf \
        -memtier-conf=./memtier.memcached.$i.conf \
        -output=../../../results/memcached/$DIR/$i/ \
        -base-port=11120 \
        -instances=1 \
        -duration=30
done

git add ../../../
git commit -m "Object size results"
git push