#!/bin/bash

for i in {1..15}
do
    for j in {1..3}
    do
        python main.py \
            -type=memcached \
            -server-conf=../configs/cpu-vs-latency/memcached.conf \
            -memtier-conf=../configs/cpu-vs-latency3/memtier.memcached.$i.conf \
            -output=../results/cpu-vs-latency2/memcached/$((i+15))-$j/
    done
done

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.1.conf \
#     -output=../results/cpu-vs-latency2/memcached/1-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.1.conf \
#     -output=../results/cpu-vs-latency2/memcached/1-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.1.conf \
#     -output=../results/cpu-vs-latency2/memcached/1-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.2.conf \
#     -output=../results/cpu-vs-latency2/memcached/2-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.2.conf \
#     -output=../results/cpu-vs-latency2/memcached/2-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.2.conf \
#     -output=../results/cpu-vs-latency2/memcached/2-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.3.conf \
#     -output=../results/cpu-vs-latency2/memcached/3-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.3.conf \
#     -output=../results/cpu-vs-latency2/memcached/3-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.3.conf \
#     -output=../results/cpu-vs-latency2/memcached/3-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.4.conf \
#     -output=../results/cpu-vs-latency2/memcached/4-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.4.conf \
#     -output=../results/cpu-vs-latency2/memcached/4-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.4.conf \
#     -output=../results/cpu-vs-latency2/memcached/4-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.5.conf \
#     -output=../results/cpu-vs-latency2/memcached/5-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.5.conf \
#     -output=../results/cpu-vs-latency2/memcached/5-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.5.conf \
#     -output=../results/cpu-vs-latency2/memcached/5-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.6.conf \
#     -output=../results/cpu-vs-latency2/memcached/6-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.6.conf \
#     -output=../results/cpu-vs-latency2/memcached/6-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.6.conf \
#     -output=../results/cpu-vs-latency2/memcached/6-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.7.conf \
#     -output=../results/cpu-vs-latency2/memcached/7-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.7.conf \
#     -output=../results/cpu-vs-latency2/memcached/7-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.7.conf \
#     -output=../results/cpu-vs-latency2/memcached/7-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.8.conf \
#     -output=../results/cpu-vs-latency2/memcached/8-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.8.conf \
#     -output=../results/cpu-vs-latency2/memcached/8-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.8.conf \
#     -output=../results/cpu-vs-latency2/memcached/8-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.9.conf \
#     -output=../results/cpu-vs-latency2/memcached/9-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.9.conf \
#     -output=../results/cpu-vs-latency2/memcached/9-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.9.conf \
#     -output=../results/cpu-vs-latency2/memcached/9-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.10.conf \
#     -output=../results/cpu-vs-latency2/memcached/10-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.10.conf \
#     -output=../results/cpu-vs-latency2/memcached/10-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.10.conf \
#     -output=../results/cpu-vs-latency2/memcached/10-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.11.conf \
#     -output=../results/cpu-vs-latency2/memcached/11-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.11.conf \
#     -output=../results/cpu-vs-latency2/memcached/11-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.11.conf \
#     -output=../results/cpu-vs-latency2/memcached/11-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.12.conf \
#     -output=../results/cpu-vs-latency2/memcached/12-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.12.conf \
#     -output=../results/cpu-vs-latency2/memcached/12-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.12.conf \
#     -output=../results/cpu-vs-latency2/memcached/12-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.13.conf \
#     -output=../results/cpu-vs-latency2/memcached/13-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.13.conf \
#     -output=../results/cpu-vs-latency2/memcached/13-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.13.conf \
#     -output=../results/cpu-vs-latency2/memcached/13-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.14.conf \
#     -output=../results/cpu-vs-latency2/memcached/14-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.14.conf \
#     -output=../results/cpu-vs-latency2/memcached/14-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.14.conf \
#     -output=../results/cpu-vs-latency2/memcached/14-3/


# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.15.conf \
#     -output=../results/cpu-vs-latency2/memcached/15-1/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.15.conf \
#     -output=../results/cpu-vs-latency2/memcached/15-2/

# python main.py \
#     -type=memcached \
#     -server-conf=../configs/cpu-vs-latency/memcached.conf \
#     -memtier-conf=../configs/cpu-vs-latency/memtier.memcached.15.conf \
#     -output=../results/cpu-vs-latency2/memcached/15-3/