#!/bin/bash

DIR=object-size-retest

for i in {1..19}
do
    python ../../../benchmark/main.py \
        -type=memcached \
        -server-conf=./memcached.conf \
        -memtier-conf=./memtier.memcached.$i.conf \
        -output=../../../results/memcached/$DIR/$i/ \
        -base-port=11120 \
        -instances=1 \
        -duration=90 \
        -pin=true
done

git add ../../../
git commit -m "Object size results"
git push